import json
import re
from fastapi import APIRouter, Depends, File, Form, UploadFile, BackgroundTasks, HTTPException
from typing import List

from app.core.security import get_current_user
from app.core.queue import get_semaphore, create_job, update_job, JobStatus
from app.core.gemini import generate
from app.services.pdf_extractor import extract_text_from_pdf
from app.services.email_sender import send_receipt_analysis

router = APIRouter(prefix="/api/receipts", tags=["receipts"])

_SYSTEM = (
    "You are an accounting assistant that analyses receipt data. "
    "You respond ONLY with a valid JSON object — no markdown, no code fences."
)

_RECEIPT_PROMPT = """
Below is the extracted text from one or more receipts.
Return a JSON object with this structure:
{{
  "receipts": [
    {{
      "vendor": "<vendor name>",
      "date": "<date or 'unknown'>",
      "items": [
        {{"description": "<item>", "quantity": <number or null>, "unit_price": <number or null>, "total": <number>}}
      ],
      "subtotal": <number or null>,
      "tax": <number or null>,
      "total": <number>,
      "currency": "<ISO currency code, e.g. USD, ZAR>"
    }}
  ],
  "grand_total": <sum of all receipt totals>,
  "summary": "<one-sentence summary>"
}}
If a field cannot be determined, use null.

Receipt text:
{text}
"""


def _build_html_email(analysis: dict) -> str:
    rows = []
    for i, receipt in enumerate(analysis.get("receipts", []), start=1):
        rows.append(
            f"<tr><td colspan='4' style='background:#f3f4f6;font-weight:bold;padding:8px'>"
            f"Receipt {i}: {receipt.get('vendor','Unknown')} — {receipt.get('date','')}</td></tr>"
        )
        for item in receipt.get("items", []):
            rows.append(
                f"<tr>"
                f"<td style='padding:6px 8px'>{item.get('description','')}</td>"
                f"<td style='padding:6px 8px;text-align:center'>{item.get('quantity','')}</td>"
                f"<td style='padding:6px 8px;text-align:right'>{item.get('unit_price','')}</td>"
                f"<td style='padding:6px 8px;text-align:right'><b>{item.get('total','')}</b></td>"
                f"</tr>"
            )
        rows.append(
            f"<tr><td colspan='3' style='text-align:right;padding:6px 8px'>Total</td>"
            f"<td style='text-align:right;padding:6px 8px'><b>{receipt.get('total','')} {receipt.get('currency','')}</b></td></tr>"
        )

    table = (
        "<table style='border-collapse:collapse;width:100%;font-family:sans-serif;font-size:14px'>"
        "<thead><tr style='background:#1d4ed8;color:white'>"
        "<th style='padding:8px;text-align:left'>Description</th>"
        "<th style='padding:8px'>Qty</th>"
        "<th style='padding:8px;text-align:right'>Unit Price</th>"
        "<th style='padding:8px;text-align:right'>Total</th>"
        "</tr></thead>"
        f"<tbody>{''.join(rows)}</tbody>"
        "</table>"
    )

    return f"""
    <div style='font-family:sans-serif;max-width:700px;margin:0 auto'>
      <h2 style='color:#1d4ed8'>Receipt Analysis</h2>
      <p>{analysis.get('summary','')}</p>
      {table}
      <p style='margin-top:16px'><b>Grand Total: {analysis.get('grand_total','')} </b></p>
      <hr/>
      <p style='color:#9ca3af;font-size:12px'>Generated by AI Accounting &amp; Auditing Portal</p>
    </div>
    """


async def _process_receipts(job_id: str, pdf_bytes_list: list[bytes], email: str) -> None:
    semaphore = get_semaphore()
    await update_job(job_id, JobStatus.PROCESSING)
    try:
        # Extract text from all PDFs
        combined_text = ""
        for i, pdf_bytes in enumerate(pdf_bytes_list):
            text = extract_text_from_pdf(pdf_bytes)
            combined_text += f"\n\n=== Document {i + 1} ===\n{text}"

        prompt = _RECEIPT_PROMPT.format(text=combined_text[:8000])  # token guard

        async with semaphore:
            raw = await generate(prompt, system_prompt=_SYSTEM)

        raw = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()
        analysis = json.loads(raw)

        html = _build_html_email(analysis)
        send_receipt_analysis(
            to_email=email,
            subject=f"Receipt Analysis — {analysis.get('summary', 'Your receipts')}",
            html_body=html,
        )

        await update_job(job_id, JobStatus.DONE, result={"email_sent_to": email, "analysis": analysis})
    except Exception as exc:  # noqa: BLE001
        await update_job(job_id, JobStatus.FAILED, error=str(exc))


@router.post("/upload")
async def upload_receipts(
    background_tasks: BackgroundTasks,
    files: List[UploadFile] = File(...),
    email: str = Form(...),
    _user: str = Depends(get_current_user),
):
    if not files:
        raise HTTPException(status_code=400, detail="No files uploaded")

    # Read all file bytes up front (can't read in background after request closes)
    pdf_bytes_list = []
    for f in files:
        if not f.content_type or "pdf" not in f.content_type.lower():
            raise HTTPException(status_code=400, detail=f"File '{f.filename}' is not a PDF")
        pdf_bytes_list.append(await f.read())

    job_id = await create_job("receipts")
    background_tasks.add_task(_process_receipts, job_id, pdf_bytes_list, email)

    return {"job_id": job_id, "status": "queued", "message": "Processing started — poll /api/jobs/{job_id} for status"}
